from __future__ import annotations

try:  # ruff: ignore[non-empty-init-module]  # _version.py is generated by setuptools-scm at build time
    from jira_ticket_mcp._version import version as __version__
except ImportError:
    __version__ = "0.0.0+unknown"

__all__ = ["__version__"]
